version: "3.8"
services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  health-monitor-service-img:
    build:
      context: .
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - MONGODB_URI=mongodb://mongo:27017/health-monitor-dev
    volumes:
      - ./:/app
    command: npm run start
volumes:
 mongodb:
 mongodb_config:

